import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000/api';
const demoItems = [
  { id: 1, source: 'youtube', title: 'The Art of the Cover Drive', description: 'A masterclass in timing, balance and beautiful batting.', category: 'cricket', creator_or_brand: 'Cricket Lab', tags: ['cricket', 'batting', 'sports'], thumbnail: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=900&q=80' },
  { id: 2, source: 'news', title: 'India’s next generation of fast bowlers', description: 'Why pace, data and fitness are reshaping the game.', category: 'sports', creator_or_brand: 'The Sporting Post', tags: ['cricket', 'fitness', 'india'], thumbnail: 'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?auto=format&fit=crop&w=900&q=80' },
  { id: 3, source: 'shopping', title: 'Pro Grip Cricket Bat', description: 'Engineered for a lighter pickup and powerful stroke play.', category: 'shopping', creator_or_brand: 'Willow & Co.', tags: ['cricket', 'batting', 'equipment'], thumbnail: 'https://images.unsplash.com/photo-1589801258579-18e091f4ca26?auto=format&fit=crop&w=900&q=80' },
  { id: 4, source: 'instagram', title: 'Morning mobility for athletes', description: 'Five moves to keep your shoulders and hips game-ready.', category: 'fitness', creator_or_brand: '@movebetter', tags: ['fitness', 'sports', 'training'], thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80' },
  { id: 5, source: 'youtube', title: 'Python in 60 minutes', description: 'Build a data project from a clean notebook.', category: 'technology', creator_or_brand: 'Code Atlas', tags: ['python', 'programming', 'technology'], thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80' },
  { id: 6, source: 'news', title: 'AI is changing the way we watch sport', description: 'The small models behind a more personal match day.', category: 'technology', creator_or_brand: 'Signal Daily', tags: ['ai', 'technology', 'sports'], thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80' }
];
const icons = { youtube: '▶', instagram: '◎', shopping: '◇', news: '✦', demo: '✦' };
const title = s => s === 'youtube' ? 'YouTube' : s === 'instagram' ? 'Instagram' : s === 'shopping' ? 'Shopping' : s === 'news' ? 'News' : 'For you';

function App() {
  const [page, setPage] = useState('home'); const [items, setItems] = useState(demoItems); const [recommendations, setRecommendations] = useState(demoItems.slice(0,4));
  const [filter, setFilter] = useState('all'); const [search, setSearch] = useState(''); const [notice, setNotice] = useState(''); const [online, setOnline] = useState(false);
  const [profile, setProfile] = useState([{tag:'cricket',score:1},{tag:'sports',score:.82},{tag:'batting',score:.71},{tag:'fitness',score:.42},{tag:'india',score:.26}]);
  const load = async () => { try { const [all, rec, interests] = await Promise.all([fetch(`${API}/items?limit=50`), fetch(`${API}/recommendations?user_id=1&limit=12`), fetch(`${API}/users/1/expanded-interests`)]); if (!all.ok || !rec.ok) throw new Error(); const allItems = await all.json(), r = await rec.json(); setItems(allItems); setRecommendations(r.recommendations.map(x => ({...x.item, score:x.score, explanation:x.explanation}))); if (interests.ok) { const p = await interests.json(); setProfile(p.map(x => ({tag:x.tag, score:x.score}))); } setOnline(true); } catch { setOnline(false); } };
  useEffect(() => { load(); }, []);
  const interact = async (item, interaction_type) => { setNotice(interaction_type === 'like' ? 'Saved your preference — refreshing your feed.' : 'Thanks — we’ll show less like this.'); try { await fetch(`${API}/interactions`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({user_id:1,item_id:item.id,interaction_type})}); await load(); } catch {} setTimeout(()=>setNotice(''), 3000); };
  const shown = useMemo(() => items.filter(i => (filter === 'all' || i.source === filter) && `${i.title} ${i.tags?.join(' ')}`.toLowerCase().includes(search.toLowerCase())), [items,filter,search]);
  const nav = [['home','Home'],['explore','Explore'],['interests','My interests'],['graph','Tag graph']];
  return <div className="app"><aside><div className="brand"><span className="brandMark">N</span><span>NEXUS</span></div><p className="eyebrow">SMART DISCOVERY</p><nav>{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><span>{id==='home'?'⌂':id==='explore'?'⌕':id==='interests'?'◒':'◌'}</span>{label}</button>)}</nav><div className="sideBottom"><div className="profileDot">AK</div><div><b>Alex Kumar</b><small>Curious explorer</small></div><button className="dots">•••</button></div></aside><main><header><div><p className="eyebrow">{page === 'home' ? 'GOOD MORNING, ALEX' : 'PERSONALIZED DISCOVERY'}</p><h1>{page === 'home' ? <>Find your next <em>favourite thing.</em></> : page === 'explore' ? 'Explore everything.' : page === 'interests' ? 'What inspires you.' : 'The map behind your feed.'}</h1></div><div className="headerRight"><span className={'status '+(online?'live':'')}>{online?'● Live connection':'● Demo mode'}</span><button className="bell">♧</button></div></header>{notice && <div className="toast">✦ {notice}</div>}{page==='home'&&<Home recs={recommendations} interact={interact} setPage={setPage}/>} {page==='explore'&&<Explore shown={shown} filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} interact={interact}/>} {page==='interests'&&<Interests profile={profile}/>} {page==='graph'&&<Graph profile={profile}/>}</main></div>;
}
function Card({item, interact, rank}) { const source = item.source || 'demo'; return <article className="card"><div className="image"><img src={item.thumbnail || item.image_url || 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=80'} alt=""/><span className={'platform '+source}>{icons[source]||'✦'} {title(source)}</span>{rank&&<span className="rank">#{rank}</span>}</div><div className="cardBody"><div className="cardMeta"><span>{item.creator_or_brand || 'Recommended for you'}</span>{item.score&&<b>{Math.round(item.score)}% match</b>}</div><h3>{item.title}</h3><p>{item.description}</p><div className="tags">{(item.tags||[]).slice(0,3).map(t=><span key={t}>#{t}</span>)}</div><div className="actions"><button onClick={()=>interact(item,'like')}>♡ Like</button><button onClick={()=>interact(item,'dislike')}>×</button><a href={item.url || item.external_url || '#'} target="_blank">Open ↗</a></div></div></article> }
function Home({recs,interact,setPage}) { return <><section className="hero"><div><span className="pill">✦ Built around you</span><h2>A feed that follows<br/>your <em>curiosity.</em></h2><p>One intelligent stream, shaped by what you enjoy across every platform.</p><button className="primary" onClick={()=>setPage('explore')}>Explore all content <span>→</span></button></div><div className="orbit"><div className="orbitCore">FOR<br/>YOU</div><i className="o1">▶</i><i className="o2">✦</i><i className="o3">◎</i><i className="o4">◇</i></div></section><section className="sectionHead"><div><p className="eyebrow">YOUR PERSONAL MIX</p><h2>Picked for you <span>✦</span></h2></div><button className="textButton" onClick={()=>setPage('explore')}>View all <span>→</span></button></section><div className="cards">{recs.slice(0,4).map((x,i)=><Card key={x.id} item={x} interact={interact} rank={i+1}/>)}</div></> }
function Explore({shown,filter,setFilter,search,setSearch,interact}) { return <><div className="tools"><div className="search">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search things to discover"/></div><div className="filters">{['all','youtube','instagram','shopping','news'].map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'selected':''}>{f==='all'?'All sources':title(f)}</button>)}</div></div><p className="resultCount">{shown.length} things waiting to be discovered</p><div className="cards exploreCards">{shown.map(x=><Card key={x.id} item={x} interact={interact}/>)}</div></> }
function Interests({profile}) { const sorted = [...profile].sort((a,b)=>b.score-a.score).slice(0,7); return <><section className="insight"><div><span className="pill">◌ YOUR INTEREST PROFILE</span><h2>Every interaction<br/>tells a <em>story.</em></h2><p>These themes are learned from what you like, save and spend time with — then expanded through our tag graph.</p></div><div className="interestPulse"><b>89%</b><span>PROFILE<br/>CONFIDENCE</span></div></section><section className="sectionHead"><div><p className="eyebrow">DIRECT + GRAPH-EXPANDED</p><h2>Your top signals</h2></div><span className="subtle">Updated just now</span></section><div className="interestList">{sorted.map((x,i)=><div className="interestRow" key={x.tag}><span className="number">0{i+1}</span><b>#{x.tag}</b><div className="bar"><i style={{width:`${Math.max(8, x.score*100)}%`}}/></div><strong>{Math.round(x.score*100)}%</strong><span className="kind">{i<3?'Direct signal':'Graph discovery'}</span></div>)}</div></> }
function Graph({profile}) { const nodes = [{name:'cricket',x:50,y:51,big:true},{name:'sports',x:50,y:16},{name:'batting',x:20,y:77},{name:'fitness',x:82,y:69},{name:'india',x:78,y:23},{name:'technology',x:18,y:25}]; const edge = [[50,51,50,16],[50,51,20,77],[50,51,82,69],[50,51,78,23],[50,16,78,23],[18,25,50,16]]; return <><div className="graphIntro"><span className="pill">◌ WEIGHTED TAG GRAPH</span><p>Nodes are interests. Lines are relationships. Thicker, warmer lines mean stronger connections.</p></div><section className="graphPanel"><div className="graphCanvas"><svg viewBox="0 0 100 100" preserveAspectRatio="none">{edge.map((e,i)=><line key={i} x1={e[0]} y1={e[1]} x2={e[2]} y2={e[3]} stroke={i<3?'#ea754a':'#bcc7c8'} strokeWidth={i<3?'1.15':'.55'}/>)}</svg>{nodes.map(n=><div key={n.name} className={'node '+(n.big?'focus':'')} style={{left:`${n.x}%`,top:`${n.y}%`}}><span>{n.name}</span></div>)}</div><aside className="legend"><p className="eyebrow">GRAPH INSIGHT</p><h3>Cricket is your<br/><em>strongest hub.</em></h3><p>It connects your direct interest in batting with inferred interests like fitness and India.</p><div className="stat"><b>{profile.length}</b><span>active interests</span></div><div className="stat"><b>12</b><span>weighted connections</span></div></aside></section></> }
createRoot(document.getElementById('root')).render(<App/>);
